// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewReport struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type Query struct {
}

type Report struct {
	ID          string `json:"id" bson:"_id"`
	Title       string `json:"title" bson:"title"`
	Description string `json:"description" bson:"description"`
	CreatedAt   string `json:"createdAt" bson:"createdAt"`
}
